// Copyright 2014 George King.
// Permission to use this file is granted in ploy/license.txt.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

int main(int argc, char* argv[]) {
  if (argc != 2) {
    fprintf(stderr, "expected a single argument specifying variable name.\n");
    exit(1);
  }
  printf("// generated by text-to-c-literal.\n\n");
  printf("static const char* %s = \n", argv[1]);
  fputc('"', stdout);
  int c = getchar();
  // note: the puts function adds a final newline so we cannot use it.
  while (c != EOF) {
    if (c == '"')         fputs("\\\"", stdout);
    else if (c == '\\')   fputs("\\\\", stdout);
    else if (c == '\n')   fputs("\\n\"\n\"", stdout);
    else if (isprint(c))  fputc(c, stdout);
    else                  printf("\\x%02x", c);
    c = getchar();
  }
  fputs("\";\n\n", stdout);
  return 0;
}
