// Copyright 2014 George King.
// Permission to use this file is granted in ploy/license.txt.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

int main(int argc, char* argv[]) {
  if (argc != 2) {
    fprintf(stderr, "expected a single argument specifying variable name.\n");
    exit(1);
  }
  printf("// generated by text-to-c-literal.\n\nstatic const char* %s =\n", argv[1]);
  putchar('"');
  int c = getchar();
  while (c != EOF) {
    if (c == '"')         fputs("\\\"", stdout);
    else if (c == '\\')   fputs("\\\\", stdout);
    else if (c == '\n')   fputs("\\n\"\n\"", stdout);
    else if (isprint(c))  putchar(c);
    else                  printf("\\x%02x", c);
    c = getchar();
  }
  puts("\";\n\n");
  return 0;
}
